# 專案級 Gradle 設定。
# IDE（如 Android Studio）使用者：
# 透過 IDE 設定的 Gradle 設定將覆寫本檔案中指定的任何設定。
# 指定 Daemon 程序的 JVM 參數，適用於調整記憶體大小。
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# 啟用 Gradle 建置快取。
org.gradle.caching=true
# 啟用 Gradle 設定快取。
org.gradle.configuration-cache=true
# 啟用 AndroidX 套件結構。
android.useAndroidX=true
# Kotlin 程式碼風格。
kotlin.code.style=official
# 啟用非傳遞性 R 類別以減少資源大小。
android.nonTransitiveRClass=true
android.uniquePackageNames=false
